#!/bin/bash

# if $1 is '-h', print brief help
if [[ "$1" = "-h" || "$1" = "--help" ]]; then
cat <<EOF
Add a list of times from standard input using day:hour:minute:second format.
All fields but seconds are optional. Field separator may be any non-numeric
character but must be consistent across each line of input. Only one
measurement of time per line.
EOF
  exit 0
fi

# check for missing dependencies
for i in tr; do
  if ! command -v $i >/dev/null; then
    echo "Dependency $i not found."
    exit 1
  fi
done

# declare -A time
declare -A time=([seconds]=0 [minutes]=0 [hours]=0 [days]=0)

# while readline is not empty
while read; do

  # identify delimiter
  delimiter=$(echo $REPLY|tr -d [0-9])
  if [[ -n $delimiter ]]; then
    if [[ -n $(echo $delimiter | tr -d ${delimiter:0:1}) ]]; then
      echo "Error: Too many non-digital characters. Invisible color codes maybe?"
      exit 1
    fi
    delimiter=${delimiter:0:1}
    REPLY=${delimiter}${REPLY}
  fi

  for i in seconds minutes hours days; do
    if [[ $REPLY != $delimiter && -n $REPLY ]]; then
      # add rightmost field to time[$i]
      time[$i]=$((10#${time[$i]} + 10#${REPLY##*$delimiter}))

      # strip ${delimiter}${REPLY##*$delimiter} from right of string
      REPLY=${REPLY%${delimiter}${REPLY##*$delimiter}}
    fi
  done

  # if string is not empty, print error and exit 1
  if [[ -n $REPLY ]]; then
    echo "Input seems to contain too many fields. Please limit to seconds, hours, minutes, days."
    exit 1
  fi

done

# add ${time[seconds]} / 60 to time[minutes]
time[minutes]=$((${time[minutes]} + (${time[seconds]} / 60)))

# time[seconds]=${time[seconds]} % 60
time[seconds]=$((${time[seconds]} % 60))

# zero fill if <= 9
if [[ ${time[seconds]} -le 9 ]]; then
  time[seconds]=0${time[seconds]}
fi

# add ${time[minutes]} / 60 to time[hours]
time[hours]=$((${time[hours]} + (${time[minutes]} / 60)))

# time[minutes]=${time[minutes]} % 60
time[minutes]=$((${time[minutes]} % 60))

# zero fill if <= 9
if [[ ${time[minutes]} -le 9 ]]; then
  time[minutes]=0${time[minutes]}
fi

# add ${time[hours]} / 24 to time[days]
time[days]=$((${time[days]} + (${time[hours]} / 24)))

# time[hours]=${time[hours]} % 24
time[hours]=$((${time[hours]} % 24))

# zero fill if <= 9
if [[ ${time[hours]} -le 9 ]]; then
  time[hours]=0${time[hours]}
fi

# print ${time[days]} ${time[hours]}  ${time[minutes]} ${time[seconds]}
echo Total time: ${time[days]}:${time[hours]}:${time[minutes]}:${time[seconds]}

exit 0
